### ISSUE TITLE
java.lang.ArithmeticException

### ISSUE THREAD

**Issue by angyone1** [Drumber/RemoteLight#23]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5-beta
Java version: 1.8.0_265 (AdoptOpenJDK)
OS: Windows 10
StackTrace:
```
java.lang.ArithmeticException: / by zero
	at de.lars.remotelightcore.scene.scenes.Jungle.onEnable(Jungle.java:60)
	at de.lars.remotelightcore.scene.SceneManager.start(SceneManager.java:82)
	at de.lars.remotelightclient.ui.panels.scenes.ScenesPanel$1.mouseClicked(ScenesPanel.java:122)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
*Apr 18, 2021 11:29 PM*

**Comment by angyone1** [comment]
sorry i'm noob ... I have to install java?

**Comment by Drumber** [comment]
Hi, thanks for reporting the bug. You don't need to install Java if you have downloaded the RemoteLight-Windows.zip archive. There is already a Java VM included.

I could reproduce the issue. The exception is thrown when using the Juggle scene with less than 15 pixels. I fixed this bug in commit 8631aa2.

**Comment by angyone1** [comment]
thanks!
