### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by angyone1** [Drumber/RemoteLight#25]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5-beta
Java version: 1.8.0_265 (AdoptOpenJDK)
OS: Windows 10
StackTrace:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at de.lars.remotelightclient.ui.panels.animations.AnimationOptionsPanel$2.onSettingChanged(AnimationOptionsPanel.java:199)
	at de.lars.remotelightclient.ui.panels.settings.settingComps.SettingPanel.onChanged(SettingPanel.java:67)
	at de.lars.remotelightclient.ui.panels.settings.settingComps.SettingBooleanPanel$1.actionPerformed(SettingBooleanPanel.java:62)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.focusLost(BasicButtonListener.java:198)
	at java.awt.Component.processFocusEvent(Component.java:6431)
	at java.awt.Component.processEvent(Component.java:6295)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:689)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at sun.awt.SunToolkit$1.run(SunToolkit.java:521)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
*May 11, 2021 7:48 AM*

**Comment by Drumber** [comment]
Thanks for reporting the bug. You can download the latest build from here: https://remotelight.github.io/
