### ISSUE TITLE
java.lang.ArithmeticException

### ISSUE THREAD

**Issue by BangDroid** [Drumber/RemoteLight#28]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5-beta
Java version: 1.8.0_265 (AdoptOpenJDK)
OS: Windows 10
StackTrace:
```
java.lang.ArithmeticException: / by zero
	at de.lars.remotelightcore.musicsync.modes.Strobe.<init>(Strobe.java:52)
	at de.lars.remotelightcore.musicsync.MusicSyncManager.registerMusicEffects(MusicSyncManager.java:385)
	at de.lars.remotelightcore.musicsync.MusicSyncManager.<init>(MusicSyncManager.java:93)
	at de.lars.remotelightcore.RemoteLightCore.<init>(RemoteLightCore.java:148)
	at de.lars.remotelightclient.Main.<init>(Main.java:108)
	at de.lars.remotelightclient.Main.main(Main.java:88)

```
*May 18, 2021 12:49 AM*

**Comment by BangDroid** [comment]
I went down too low with the strobes / second value. RemoteLight started acting strange so I closed it. Now it wont re-open.
I'll try to fix by editing config.

**Comment by Drumber** [comment]
Thanks for reporting. Open the data.json, search for `musicsync.strobe.flashratio` and set the value to somtehing greater than 0. This should allow you to start remotelight again.

**Comment by BangDroid** [comment]
Cheers yeah I did this.
