### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ChemaBautista** [Drumber/RemoteLight#34]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5
Commit ID: bf23004
Java version: 1.8.0_302 (Temurin)
OS: Mac OS X
StackTrace:
```
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:147)
	at de.lars.remotelightclient.ui.panels.settings.settingComps.SettingIntPanel.<init>(SettingIntPanel.java:59)
	at de.lars.remotelightclient.utils.SettingsUtil.getSettingPanel(SettingsUtil.java:50)
	at de.lars.remotelightclient.ui.panels.screencolor.ScreenColorPanel.addOptions(ScreenColorPanel.java:226)
	at de.lars.remotelightclient.ui.panels.screencolor.ScreenColorPanel.<init>(ScreenColorPanel.java:138)
	at de.lars.remotelightclient.ui.menu.DefaultMenuPanelFactory.getMenuPanel(DefaultMenuPanelFactory.java:76)
	at de.lars.remotelightclient.ui.MainFrame.showMenuPanel(MainFrame.java:266)
	at de.lars.remotelightclient.ui.menu.sidemenu.SideMenu.onMenuItemClicked(SideMenu.java:158)
	at de.lars.remotelightclient.ui.menu.sidemenu.SideMenuExtended.onMenuItemClicked(SideMenuExtended.java:84)
	at de.lars.remotelightclient.ui.menu.sidemenu.SideMenu$2.actionPerformed(SideMenu.java:149)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
*Aug 31, 2021 7:27 AM*

**Comment by Drumber** [comment]
Hey, thanks for reporting. I just have one question so I can reproduce the error:
What values did you have for **Scan Area X/Y** and **Scan Area Width/Height** (in the ScreenColor settings) when the error occurred?

**Comment by ChemaBautista** [comment]
Scan Area x/y = 0 
Width = 1900
Height = 800

**Comment by Drumber** [comment]
I could not reproduce the error. Does the error still occur or has it fixed itself?
If this was only a one-time error, I would close this issue, since I'm currently working on a recode where I update the whole code base anyway.

**Comment by ChemaBautista** [comment]
Only reset config.
