### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ChemaBautista** [Drumber/RemoteLight#35]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5
Commit ID: bf23004
Java version: 16.0.2 (Oracle Corporation)
OS: Mac OS X
StackTrace:
```
java.lang.UnsatisfiedLinkError: Unable to load library 'linux-x64/libxt-core.so': Native library (darwin/liblinux-x64/libxt-core.so.dylib) not found in resource path (/Users/ch3ma/Downloads/RemoteLight-0.2.5.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.xtaudio.xt.XtNative.init(XtNative.java:154)
	at com.xtaudio.xt.XtAudio.<init>(XtAudio.java:35)
	at de.lars.remotelightclient.ui.panels.musicsync.nativesound.NativeSoundConfigPanel.setValues(NativeSoundConfigPanel.java:106)
	at de.lars.remotelightclient.ui.panels.musicsync.nativesound.NativeSoundConfigPanel.<init>(NativeSoundConfigPanel.java:98)
	at de.lars.remotelightclient.ui.panels.musicsync.nativesound.NativeSoundConfigPanel.showDialog(NativeSoundConfigPanel.java:357)
	at de.lars.remotelightclient.ui.panels.musicsync.MusicSyncOptionsPanel$5.actionPerformed(MusicSyncOptionsPanel.java:357)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
*Aug 31, 2021, 9:06 AM*

**Comment by Drumber** [comment]
The error is related to a library not supporting Mac OS. Therefore the "Configure NativeSound" button is now hidden on Mac OS since the sound library (xt-audio) does not support it.

The build with the fix should be downloadable [here](https://remotelight.github.io/) in a few minutes.
