### ISSUE TITLE
com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by josedurazoc** [Drumber/RemoteLight#36]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5
Commit ID: bf23004
Java version: 1.8.0_292 (AdoptOpenJDK)
OS: Windows 10
StackTrace:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at de.lars.remotelightcore.colors.palette.PaletteLoader.load(PaletteLoader.java:73)
	at de.lars.remotelightcore.RemoteLightCore.<init>(RemoteLightCore.java:137)
	at de.lars.remotelightclient.Main.<init>(Main.java:119)
	at de.lars.remotelightclient.Main.main(Main.java:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 5 more

```
*Sep 27, 2021 12:03 AM*

**Comment by Drumber** [comment]
Hi, thanks for reporting.
The error occured when the color palettes were not saved properly. The corrupted data file then caused a crash with your reported exception when loading the palettes on the next program start.

Please delete the `palettes.json` file in `%userprofile%/.RemoteLight` to reset the color palettes. Otherwise RemoteLight might not start.

I've fixed the problem in [release v0.2.5.2](https://github.com/Drumber/RemoteLight/releases/tag/v0.2.5.2).
