### ISSUE TITLE
com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by notryanfraser** [Drumber/RemoteLight#37]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.5
Commit ID: bf23004
Java version: 16.0.2 (Microsoft)
OS: Windows 10
StackTrace:
```
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 890 column 4 path $[19]
	at com.google.gson.Gson.fromJson(Gson.java:942)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at de.lars.remotelightcore.colors.palette.PaletteLoader.load(PaletteLoader.java:73)
	at de.lars.remotelightcore.RemoteLightCore.<init>(RemoteLightCore.java:137)
	at de.lars.remotelightclient.Main.<init>(Main.java:119)
	at de.lars.remotelightclient.Main.main(Main.java:96)
Caused by: java.io.EOFException: End of input at line 890 column 4 path $[19]
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1397)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:468)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 5 more

```
*Oct 6, 2021, 11:54 AM*

I've tried using the adoptOpenJDK and Microsoft OpenJDK, but I get the same result in 0.2.5, 0.2.4 seems to start fine

**Comment by Drumber** [comment]
Hi, thanks for reporting.
The error occured when the color palettes were not saved properly. The corrupted data file then caused a crash with your reported exception when loading the palettes on the next program start.

Please delete the `palettes.json` file in `%userprofile%/.RemoteLight` to reset the color palettes. Otherwise RemoteLight might not start.

I've fixed the problem in [release v0.2.5.2](https://github.com/Drumber/RemoteLight/releases/tag/v0.2.5.2).
