### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by CaptainLynk** [Drumber/RemoteLight#5]
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.2
OS: Windows 10
StackTrace:
```
java.lang.NullPointerException
	at de.lars.remotelightcore.devices.arduino.ComPort.openPort(ComPort.java:84)
	at de.lars.remotelightcore.devices.arduino.Arduino.connect(Arduino.java:69)
	at de.lars.remotelightcore.devices.Device.onActivate(Device.java:78)
	at de.lars.remotelightcore.out.OutputManager.activate(OutputManager.java:90)
	at de.lars.remotelightcore.out.OutputManager.setActiveOutput(OutputManager.java:78)
	at de.lars.remotelightcore.SetupHelper$1.run(SetupHelper.java:114)
	at java.lang.Thread.run(Unknown Source)

```
*Jul 15, 2020 3:54 PM*

**Comment by Drumber** [comment]
Thanks for your report, the fix will be included in the next release.
